
#        spring.jpa.show-sql=true
#        spring.h2.console.enabled=true
#        server.port=8081
#        spring.datasource.url=jdbc:h2:mem:testdb
#        spring.datasource.driverClassName=org.h2.Driver
#        spring.datasource.username=sa
#        spring.datasource.password=password
#        spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  #    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
    username: sa
    password:
